# Generated by Django 3.2.18 on 2023-04-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placard', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
